### Get all reports
GET https://localhost:5001/api/v1/admin/reporting/all-reports

### Get all active reports
GET https://localhost:5001/api/v1/reporting/active-reports

### Get all available report sources for new report
GET https://localhost:5001/api/v1/admin/reporting/new-report/available-report-sources

### Get report details by key for user
GET https://localhost:5001/api/v1/reporting/report/{key}

### Get report details by key for admin
GET https://localhost:5001/api/v1/admin/reporting/report/{key}

### Create a new report
POST https://localhost:5001/api/v1/admin/reporting/new-report
Content-Type: application/json

{
  "model": {
    "key": "report_key",
    "reportSourceId": 1,
    "name": "Report Name",
    "description": "Report Description",
    "isActive": true,
    "hasParameters": false,
    "createdByUser": "username"
  }
}

### Update a report
PUT https://localhost:5001/api/v1/admin/reporting/update-report
Content-Type: application/json

{
  "model": {
    "key": "report_key",
    "name": "Updated Report Name",
    "description": "Updated Report Description",
    "isActive": true,
    "updatedByUser": "username"
  }
}

### Activate a report
PUT https://localhost:5001/api/v1/admin/reporting/activate-report
Content-Type: application/json

{
  "model": {
    "key": "report_key",
    "updatedByUser": "username"
  }
}

### Disable a report
PUT https://localhost:5001/api/v1/admin/reporting/deactivate-report
Content-Type: application/json

{
  "model": {
    "key": "report_key",
    "updatedByUser": "username"
  }
}

### Delete a report
DELETE https://localhost:5001/api/v1/admin/reporting/remove-report
Content-Type: application/json

{
  "model": {
    "key": "report_key"
  }
}

### Execute a report
POST https://localhost:5001/api/v1/reporting/data
Content-Type: application/json

{
  "model": {
    "key": "report_key",
    "parameters": {
      "param1": "value1",
      "param2": "value2"
    }
  }
}

### Download a report
POST https://localhost:5001/api/v1/reporting/file
Content-Type: application/json

{
  "model": {
    "key": "report_key",
    "parameters": {
      "param1": "value1",
      "param2": "value2"
    }
  }
}

